import{a as L,S as b,i as a}from"./assets/vendor-BAQQTdrx.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function e(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(t){if(t.ep)return;t.ep=!0;const r=e(t);fetch(t.href,r)}})();const w="55642648-716ae2e3c36078de20c00cb22",B="https://pixabay.com/api/";async function u(s,o=1){try{return(await L.get(B,{params:{key:w,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}})).data}catch(e){throw console.error("Помилка при запиті до Pixabay:",e),e}}const f=document.querySelector(".gallery"),p=document.getElementById("loader"),m=document.querySelector(".load-more"),I=new b(".gallery a",{captions:!0,captionsData:"alt",captionPosition:"bottom"});function y(s){const o=s.map(e=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${e.largeImageURL}">
          <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
        </a>
        <div class="image-info">
          <div class="info-item"><span class="info-label">Likes</span><span class="info-value">${e.likes}</span></div>
          <div class="info-item"><span class="info-label">Views</span><span class="info-value">${e.views}</span></div>
          <div class="info-item"><span class="info-label">Comments</span><span class="info-value">${e.comments}</span></div>
          <div class="info-item"><span class="info-label">Downloads</span><span class="info-value">${e.downloads}</span></div>
        </div>
      </li>`).join("");f.insertAdjacentHTML("beforeend",o),I.refresh()}function P(){f.innerHTML=""}function h(){p.classList.remove("hidden")}function g(){p.classList.add("hidden")}function v(){m.classList.remove("hidden")}function l(){m.classList.add("hidden")}let n=1,d="";const S=document.querySelector(".load-more"),q=document.querySelector(".form");q.addEventListener("submit",async s=>{s.preventDefault();const o=s.currentTarget.elements["search-text"].value.trim();if(o){d=o,n=1,P(),l(),h();try{const e=await u(d,n);if(e.hits.length===0){a.error({message:"Нічого не знайдено!"});return}y(e.hits),e.totalHits>15?v():(l(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",transitionIn:"fadeInUp"}))}catch{a.error({message:"Помилка сервера!"})}finally{g()}}});S.addEventListener("click",async()=>{n+=1,h(),l();try{const s=await u(d,n);y(s.hits);const o=document.querySelector(".gallery-item");if(o){const i=o.getBoundingClientRect().height;window.scrollBy({top:i*2,behavior:"smooth"})}const e=Math.ceil(s.totalHits/15);n>=e?(l(),setTimeout(()=>{a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",transitionIn:"fadeInUp",setTimeout:5e3})},500)):v()}catch{a.error({message:"Помилка!"})}finally{g()}});
//# sourceMappingURL=index.js.map
