import{a as L,S as b,i}from"./assets/vendor-BAQQTdrx.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function e(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(t){if(t.ep)return;t.ep=!0;const r=e(t);fetch(t.href,r)}})();const w="55642648-716ae2e3c36078de20c00cb22",B="https://pixabay.com/api/";async function u(o,s=1){try{return(await L.get(B,{params:{key:w,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:15}})).data}catch(e){throw console.error("Помилка при запиті до Pixabay:",e),e}}const f=document.querySelector(".gallery"),m=document.getElementById("loader"),p=document.querySelector(".load-more"),P=new b(".gallery a",{captions:!0,captionsData:"alt",captionPosition:"bottom"});function y(o){const s=o.map(e=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${e.largeImageURL}">
          <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
        </a>
        <div class="image-info">
          <div class="info-item"><span class="info-label">Likes</span><span class="info-value">${e.likes}</span></div>
          <div class="info-item"><span class="info-label">Views</span><span class="info-value">${e.views}</span></div>
          <div class="info-item"><span class="info-label">Comments</span><span class="info-value">${e.comments}</span></div>
          <div class="info-item"><span class="info-label">Downloads</span><span class="info-value">${e.downloads}</span></div>
        </div>
      </li>`).join("");f.insertAdjacentHTML("beforeend",s),P.refresh()}function S(){f.innerHTML=""}function h(){m.classList.remove("hidden")}function g(){m.classList.add("hidden")}function v(){p.classList.remove("hidden")}function c(){p.classList.add("hidden")}let a=1,d="";const q=document.querySelector(".load-more"),M=document.querySelector(".form");M.addEventListener("submit",async o=>{o.preventDefault();const s=o.currentTarget.elements["search-text"].value.trim();if(s){d=s,a=1,S(),c(),h();try{const e=await u(d,a);if(e.hits.length===0){i.error({message:"Нічого не знайдено!"});return}y(e.hits),e.totalHits>15&&v()}catch{i.error({message:"Помилка сервера!"})}finally{g()}}});q.addEventListener("click",async()=>{a+=1,h(),c();try{const o=await u(d,a);y(o.hits);const s=document.querySelector(".gallery-item");if(s){const n=s.getBoundingClientRect().height;window.scrollBy({top:n*2,behavior:"smooth"})}const e=Math.ceil(o.totalHits/15);a>=e?(c(),i.info({message:"We're sorry, but you've reached the end of search results."})):v()}catch{i.error({message:"Помилка!"})}finally{g()}});
//# sourceMappingURL=index.js.map
